refactor: removes debug/macho and GetFile
goretk/gore pull request #103
Opened 2024-10-16 13:16 UTC by Zxilly

Closes: #101 
Closes: #102

2024-10-18 05:36 UTC, Zxilly commented
@TcM1911 Can you take a look at this patch?
By the way, I would like to join the `goretk` organization to better maintain this project.

2024-10-18 15:43 UTC, TcM1911 requested changes
It all looks good. The only thing I have a question about is the decision to remove a public method.

2024-10-18 15:43 UTC, TcM1911 commented on file.go
> -func (f *GoFile) GetFile() *os.File {
This is removing an exported method which likely will break some stuff downstream. I know it's not a 1.0 version yet so breakage is not guaranteed but I like to avoid it as much as possible.

2024-10-18 18:08 UTC, Zxilly commented on file.go
> -func (f *GoFile) GetFile() *os.File {
Since we didn't hold a `*os.File` right now, there's no way to keep providing this API.

2024-10-18 18:14 UTC, Zxilly commented on file.go
> -func (f *GoFile) GetFile() *os.File {
https://github.com/search?q=lang%3AGo+github.com%2Fgoretk%2Fgore&type=code

Additionally, I performed a search in GitHub and no repositories seem to be calling this API except for my project https://github.com/Zxilly/go-size-analyzer.

2024-10-20 14:15 UTC, TcM1911 approved these changes

2024-10-20 14:16 UTC, merged