add GetGoRoot
goretk/gore pull request #42
Opened 2021-06-28 05:36 UTC by boy-hack

2021-06-30 19:26 UTC, TcM1911 requested changes
Thank you for contributing. I think this is a great additional feature to the project. 

I've provided some suggestions and before I can merge this I'd like to have some tests around this. The project uses a set of known golden files that can be used for tests. There are some helper functions to resolve the paths for the files. See `TestGetTypes` for how they can be used. The `CONTRIBUTING.md` doc explains how you can either download prebuilt binaries or build them yourself.

All the golden files should have a GOROOT of `/usr/local/go`.

2021-07-01 07:56 UTC, boy-hack commented
Hello, I have solved it according to the suggestion and added a test case to goroot_test.go, but the test case shows that the go version from 1.5 to 1.9 will not be recognized. I don’t know how to modify this part

2021-07-02 22:35 UTC, TcM1911 commented
Can you take a look at how the string is addressed in the older versions? Strings are represented as:
```go
type str struct {
  data ptr
  len int
}
```
In the logic for extracting the version string, it looks for a pointer to the beginning of this struct. After that I read either two uint32 or uint64 depending on word size used to get were the string starts and the length. It's possible that in older versions, the address and length are directly moved into the register without dereference it. That may be the issue.

2021-07-05 09:09 UTC, boy-hack commented
I have added the code to get goroot to support go versions between 1.5 and 1.9. It supports darwin and linux. Windows doesn’t seem to work because I didn’t find goroot string in the windows binary.

2021-07-06 16:07 UTC, TcM1911 commented
It looks like the functionality you are using in the `time` package was added in [Go 1.10](https://golang.org/doc/go1.10). For the Windows test cases 1.5 to 1.9, can you add a check that the correct error is returned instead?

2021-07-06 16:18 UTC, boy-hack commented
@TcM1911 I don't know how to make elegant test cases, can you help me?

2021-07-06 16:24 UTC, TcM1911 commented
The variable `test` should be the filename, so you could do something like this after the `Open` call.
```go
switch test {
   case gold-windows-amd64-1.9.0:
   case gold-windows-386-1.9.0:
   ....
      r.Equal(Err.., err)
   default:
     // To original part of the code
 }
 Just add a small comment to note why the specific files are checked for an error...

2021-07-07 07:42 UTC, boy-hack commented
Thank you, I have updated it and now it works very well

2021-07-08 19:01 UTC, TcM1911 approved these changes

2021-07-08 19:02 UTC, merged